<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mmui" nsURI="IMSE" nsPrefix="IMSE">
  <eClassifiers xsi:type="ecore:EClass" name="ElementUI">
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//ElementUI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="question" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckBox" eSuperTypes="#//ElementUI"/>
  <eClassifiers xsi:type="ecore:EClass" name="Radio" eSuperTypes="#//ElementUI">
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//Options"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//ElementUI">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbCaracMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextArea" eSuperTypes="#//ElementUI">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbColonnes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbLignes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DropDown" eSuperTypes="#//ElementUI">
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//Options" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Options">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layout">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstElement" eType="#//ElementUI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listeElementUI" upperBound="-1"
        eType="#//ElementUI" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
